// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDu1IwbwjxGhAXx4kPza5w2Qzdsa7lZIU',
    appId: '1:510697787645:web:e7f206ef73a7dcdc516e94',
    messagingSenderId: '510697787645',
    projectId: 'mvc-flutter',
    authDomain: 'mvc-flutter.firebaseapp.com',
    storageBucket: 'mvc-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtn_Pycl1ckh0-wsYCak91VcHbvirXuD4',
    appId: '1:510697787645:android:ebee1097b39ebe50516e94',
    messagingSenderId: '510697787645',
    projectId: 'mvc-flutter',
    storageBucket: 'mvc-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmiQJ0avrlvgGhMkXfzmUZRc4D0i5XVsk',
    appId: '1:510697787645:ios:70fe1b97def6ae99516e94',
    messagingSenderId: '510697787645',
    projectId: 'mvc-flutter',
    storageBucket: 'mvc-flutter.appspot.com',
    iosBundleId: 'flutter.mvc.app',
  );
}
